language: node_js
node_js:
- '8'
dist: trusty
services:
- mongodb
env:
- NODE_ENV=ci PORT=3000
cache:
  directories:
  - node_modules
  - client/node_modules
install:
- npm install
- npm run build
script:
- nohup npm run start &
- sleep 3
- npm run testAll
deploy:
  provider: heroku
  api_key:
    secure: MqTsdLBUIl3cbOR+I4sFm46UqW6SFgSIrvQ4Z/YIEyW6eSS0n3lT9ZWwboKalODH2E1cceulG4DptpY4BHOyf1/2/XA9h5jP74Z/1uOpYxFclOFYPbEPGxrt3MiP/9aUY3bTkmnEIdPdrBpYOfplsM1Ii4wzqpM5bvTSauNRiqsrP06jDKsCDNyaYEkpVB/7Z0xGdiXjBwHZ/wEYJMYBQKZnyf1jKISgtkRCtxmpCL46jOnbpA/cdRgs1EVfF48ZsHPKprmLfvSNomFb6Cpz71lDqkeoq9z2lUYMB1wRKzTGtCbiPgjR1eOoApqEhjyINqrVkGEe9bxmyUvoiC14/ZqmO1ZqA6ABywGmvFGuSmJBA4HVLs+wb0skquHMxRouAgAdLSWPqB7irU7NN8v3ZSxow1cKVcT9qdzkW1logwBI0NuVnhwuIBQiNff1ATMOohJQdBiEX0tKKyGrJeNhMX+LSlsKkbfOEmWNiCNsQL2OPDISGT3E3RxIfNCq4cvkbTZ6yKyBtjGn/4cxG5OAkSrkviZw64Lluxx4z0GgStUS/PS12R9mDvfgijtMD6iepjVaDIA43/jp3mtdCI29qd6yHWx10GeI9n5UAjcAp4xS8AEjwcn7V1shSrr+4EbezGxAIUlPa/Ca4sWHrgTaWGIN+ckFQ6e0WO63Pbkub/E=
  app: ramosrecipes