language: node_js
node_js:
- '8'
dist: trusty
services:
- mongodb
env:
- NODE_ENV=ci PORT=3000
cache:
  directories:
  - node_modules
  - client/node_modules
install:
- npm install
- npm run build
script:
- nohup npm run start &
- sleep 3
- npm run testAll
deploy:
  api_key:
    secure: MQXGNPjwdFFNDkj5jAPIZGrKv3j1lakMTW8NQYNijyMkyl4WWF11yyR7dg7FwEFlAFGsUNxSiZBqMHa/SSgDtimD1jm/DRsG7hG1W0vdKfprZmd9L41FZjALKDTLWG6g5fyraaerFEkM3mwTpTM8j3TtRShd5qNimOTDpcUmdVj4LiuRk2ToXP2xDqg03HMHK2Re9FOrCoMQogHGA3Bh0wzdwS2GRIzxrE6gOyMLJYHvej3OrAXOLvjodhfr6EFe+pDt4C95Rn4ieE0a0EELsCS8b2ebsDvmCLnwyg1wwl3gykWEAg5JkP0Zf+62xFaPoCmZQdovKDjMZ0d66zCIGIRPFQYbI1QnA2RdueGr7J0E0cnpfmEoQY40Y694vjSWCW9r8HbDQyT/deQcqlWd4OdDftcS3rneAmCP+bE0gKqm2/TRxMJ4ODJo1ZWDAyqJeyM5Fpce2ednvTk3DsYiUvnXqP47MhpNZu/n8sQo1ZM+In0LmDo6/ZgKOJmJSHx1ioZMXJm1L4vgmLYABIu96q8SCccF7MY5GjwcsN/55Ks9OzisGEtC7nHArJ4aKw1q5KCqb+lpAmMeTFwDWgLXWG8Hidr+Z22boUjmOcGMAAXJ/2mS9YyZb6sqMbqcyaFw0E1pz5/wO2mHqBdmwNSVp6rsis31/EFq2xB7Jslraho=
    app: ramosrecipes